### ISSUE TITLE
MDR1986VE9x.svd

### ISSUE THREAD

**Issue by lamer0k** [StartMilandr/MDR_Pack_v6#2]
В файле: MDR1986VE9x.svd, https://github.com/StartMilandr/MDR_Pack_v6/blob/master/SVD_Files/_src/MDR1986VE9x.svd

Некорректно написно наследование полей в строках с 2861 по 2877. Например, вместо 
```
            <field derivedFrom="MDR_ADC.ADC1_Cfg.ADON">
            </field>
```
должно быть
```
            <field derivedFrom="MDR_ADC.ADC1_Cfg.ADON">
              <name>ADON</name>
              <description>Enable ADC</description>
              <bitRange>[0:0]</bitRange>
            </field>
```
Из-за этого не могу сгенерить файл *.hpp с заголовчниками.

**Comment by StartMilandr** [comment]
Keil-овская утилита SVDConv.exe это переваривает, вот результат - https://github.com/StartMilandr/MDR_Pack_v6/blob/master/SVD_Files/_out/out/MDR1986VE9x.h

А какая утилита не генерит *.hpp?

**Comment by lamer0k** [comment]
Вот эта...
https://github.com/posborne/cmsis-svd


Она правда ещё массив полей не поддерживает, но это решаемо, а вот
наследование полей требует указания как минимум имени, описания и оффсета.

вт, 22 окт. 2019 г., 17:58 StartMilandr <notifications@github.com>:

**Comment by lamer0k** [comment]
Получается что то типа этого...

https://emerson.sendthisfile.com/shared/file/download.jsp?t=WZeYr4QgaS365JlBi802jz2o&n=GVE4RAR8cpiwSWYxfXedExtc



https://emerson.sendthisfile.com/c.jsp?t=WZeYr4QgaS365JlBi802jz2o&n=GVE4RAR8cpiwSWYxfXedExtc



вт, 22 окт. 2019 г., 17:58 StartMilandr <notifications@github.com>:

**Comment by StartMilandr** [comment]
Добавил
